import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter Likes Graph</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Twitter Likes Graph</h1>
        <div className={styles.card} onClick={fetchLikes}>Sup</div>
      </main>


    </div>
  )
}

// async function fetchSomething() {
//   let response = await fetch("https://api.coindesk.com/v1/bpi/currentprice.json")
//   let responseJson: object = await response.json()
//   console.log(responseJson)
// }

async function fetchLikes() {
  const queryString = "?pages_to_fetch=10"
  try {
    let response = await fetch(`/api/fetch-twitter-likes${queryString}`)
    let responseJson = await response.json()
  } catch (error) {
    console.error(error)
  }
}

export default Home
