import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Dispatch, SetStateAction, useEffect, useRef, useState } from 'react'
import styles from '../styles/Home.module.css'
import * as d3 from "d3"
import "d3-time-format"
const parseTime = d3.timeParse("%d-%b-%y");
import BarChart from "../components/Chart1"
import BarChart2 from '../components/Chart2'


const GraphPage: NextPage = () => {
  const [data, setData] = useState("")

  useEffect(() => {
    // createGraph()
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter Likes Graph</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <div>
          <BarChart />
        </div>
          
        <Link href="/">go back</Link>
        <div >
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          {data}
        </div>
      </main>


    </div>
  )
}

async function loadLikes(setData: Dispatch<SetStateAction<string>>) {
  let response = await fetch("/api/get-locally-stored-likes")
  let responseJson = await response.json()
  setData(responseJson.data)
}

export default GraphPage
