import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Dispatch, SetStateAction, useState } from 'react'
import styles from '../styles/Home.module.css'

const GraphPage: NextPage = () => {
  const [data, setData] = useState("")
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter Likes Graph</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/">go back</Link>
        <div onClick={() => {loadLikes(setData)}}>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          {data}
        </div>
      </main>


    </div>
  )
}

async function loadLikes(setData: Dispatch<SetStateAction<string>>) {
  let response = await fetch("/api/get-locally-stored-likes")
  let responseJson = await response.json()
  setData(responseJson.data)
}

export default GraphPage
